# Generated by Django 4.1.7 on 2023-03-21 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipefavorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Маловато будет! Измените время приготовления!'), django.core.validators.MaxValueValidator(600, 'Слишком долго! Измените время приготовления!')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Маловато ингредиентов! Точнее их вообще нет...'), django.core.validators.MaxValueValidator(2000, 'Многовато будет! Давайте поменьше...')], verbose_name='Количество ингредиента'),
        ),
    ]
