# Generated by Django 4.1.7 on 2023-03-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Заблокированный токен', 'verbose_name_plural': 'Заблокированные токены'},
        ),
    ]
